### ISSUE TITLE
Doubts about the code

### ISSUE THREAD

**Issue by aozeyu** [lokeshgupta1981/SpringExamples#14]
@lokeshgupta1981 Hello, I have some doubts about some of your code in this library, I would like to ask, what is the function of the following code, I tried Google but still didn't understand it.
<img width="564" alt="截屏2022-11-06 18 03 04" src="https://user-images.githubusercontent.com/55688386/200164766-ba943b53-3580-4618-8727-2885280e75b1.png">

**Comment by aozeyu** [comment]
@lokeshgupta1981 @Wiktor89

**Comment by lokeshgupta1981** [comment]
Can you please let me know the URL of the file or link to the post where you are referring.
