### ISSUE TITLE
Inquiries

### ISSUE THREAD

**Issue by david-kariuki** [lokeshgupta1981/SpringExamples#19]

**Comment by david-kariuki** [comment]
Hi @lokeshgupta1981 
The repo looks interesting. What is this about?

**Comment by lokeshgupta1981** [comment]
What part did you not understand in the READMe file of the project?

**Comment by david-kariuki** [comment]
Ow sorry I missed that

**Comment by lokeshgupta1981** [comment]
No problem. Cheers!
